[package]
name = "pilot-os"
version = "0.1.0"
edition = "2021"

[build]
build-std = ["core", "compiler_builtins"]

# Disable Stack Unwinding when panic is triggered. Implement Custom Unwinding L$
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]